name: Update Channels by Country

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget pup

      - name: Download the webpage using wget
        run: |
          wget -q "https://www.open-epg.com/app/index.php" -O page.html

      - name: Extract country names and channel data
        run: |
          # Extract country names (modify selector as needed)
          cat page.html | pup 'selector-for-countries text{}' > countries.txt

          # Extract channels per country and save to their own files
          while read country; do
            echo "Extracting channels for $country"
            echo "=== $country ===" > "$country.txt"
            # Extract channels for this country (modify selector as needed)
            cat page.html | pup "selector-for-channels text{}" >> "$country.txt"
            echo "" >> "$country.txt"
          done < countries.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.txt
          git commit -m "Update channel data by country" || echo "No changes to commit"
          git push --force origin main
